Repository PolicyEngine/policyengine-us-data, pull requests merged in 2025-05, with the labels that each got.

#220 Impute tips
  .github/workflows/code_changes.yaml
  .github/workflows/pr_code_changes.yaml
  .gitignore
  changelog_entry.yaml
  policyengine_us_data/datasets/cps/cps.py
  policyengine_us_data/datasets/sipp/__init__.py
  policyengine_us_data/datasets/sipp/sipp.py
  policyengine_us_data/storage/download_public_prerequisites.py
  policyengine_us_data/tests/test_datasets/test_enhanced_cps.py
  policyengine_us_data/utils/loss.py
  pyproject.toml
Labels: enhancement

#228 Calibrate QBID against tax expenditure report
  changelog_entry.yaml
  policyengine_us_data/datasets/puf/puf.py
  policyengine_us_data/utils/loss.py
Labels: enhancement

#251 Run lite versions of imputations and calibrations in tests
  .github/workflows/pr_code_changes.yaml
  changelog_entry.yaml
  policyengine_us_data/datasets/cps/cps.py
  policyengine_us_data/datasets/cps/enhanced_cps.py
  policyengine_us_data/datasets/cps/extended_cps.py
  policyengine_us_data/datasets/puf/puf.py
  policyengine_us_data/datasets/sipp/sipp.py
Labels: enhancement

#259 Overtime occupation variable
  policyengine_us_data/datasets/cps/census_cps.py
  policyengine_us_data/datasets/cps/cps.py
  policyengine_us_data/tests/test_datasets/test_cps.py
Labels: enhancement

#273 Data upload is missing HF token
  changelog_entry.yaml
  policyengine_us_data/utils/data_upload.py
Labels: bug

#274 Add QBI qualification probabilities
  policyengine_us_data/datasets/cps/cps.py
Labels: codex

#275 Fix post merge workflow
  .github/workflows/code_changes.yaml
Labels: codex
